// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: club/ClubGame.proto

package com.leyou.common.protobuf.club;

public final class ClubGame_pb {
  private ClubGame_pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClubGameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // required int32 gameType = 3;
    boolean hasGameType();
    int getGameType();
    
    // optional int32 onlineTableNum = 4;
    boolean hasOnlineTableNum();
    int getOnlineTableNum();
    
    // optional int32 totalTable = 5;
    boolean hasTotalTable();
    int getTotalTable();
    
    // optional string gameConf = 6;
    boolean hasGameConf();
    String getGameConf();
  }
  public static final class ClubGame extends
      com.google.protobuf.GeneratedMessage
      implements ClubGameOrBuilder {
    // Use ClubGame.newBuilder() to construct.
    private ClubGame(Builder builder) {
      super(builder);
    }
    private ClubGame(boolean noInit) {}
    
    private static final ClubGame defaultInstance;
    public static ClubGame getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClubGame getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leyou.common.protobuf.club.ClubGame_pb.internal_static_ClubGame_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leyou.common.protobuf.club.ClubGame_pb.internal_static_ClubGame_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 gameType = 3;
    public static final int GAMETYPE_FIELD_NUMBER = 3;
    private int gameType_;
    public boolean hasGameType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getGameType() {
      return gameType_;
    }
    
    // optional int32 onlineTableNum = 4;
    public static final int ONLINETABLENUM_FIELD_NUMBER = 4;
    private int onlineTableNum_;
    public boolean hasOnlineTableNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getOnlineTableNum() {
      return onlineTableNum_;
    }
    
    // optional int32 totalTable = 5;
    public static final int TOTALTABLE_FIELD_NUMBER = 5;
    private int totalTable_;
    public boolean hasTotalTable() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getTotalTable() {
      return totalTable_;
    }
    
    // optional string gameConf = 6;
    public static final int GAMECONF_FIELD_NUMBER = 6;
    private java.lang.Object gameConf_;
    public boolean hasGameConf() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getGameConf() {
      java.lang.Object ref = gameConf_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gameConf_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGameConfBytes() {
      java.lang.Object ref = gameConf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gameConf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      gameType_ = 0;
      onlineTableNum_ = 0;
      totalTable_ = 0;
      gameConf_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGameType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, gameType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, onlineTableNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, totalTable_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getGameConfBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gameType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, onlineTableNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, totalTable_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getGameConfBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.leyou.common.protobuf.club.ClubGame_pb.ClubGame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.leyou.common.protobuf.club.ClubGame_pb.ClubGame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.leyou.common.protobuf.club.ClubGame_pb.ClubGameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leyou.common.protobuf.club.ClubGame_pb.internal_static_ClubGame_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leyou.common.protobuf.club.ClubGame_pb.internal_static_ClubGame_fieldAccessorTable;
      }
      
      // Construct using com.leyou.common.protobuf.club.ClubGame_pb.ClubGame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        gameType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        onlineTableNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        totalTable_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        gameConf_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leyou.common.protobuf.club.ClubGame_pb.ClubGame.getDescriptor();
      }
      
      public com.leyou.common.protobuf.club.ClubGame_pb.ClubGame getDefaultInstanceForType() {
        return com.leyou.common.protobuf.club.ClubGame_pb.ClubGame.getDefaultInstance();
      }
      
      public com.leyou.common.protobuf.club.ClubGame_pb.ClubGame build() {
        com.leyou.common.protobuf.club.ClubGame_pb.ClubGame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.leyou.common.protobuf.club.ClubGame_pb.ClubGame buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.leyou.common.protobuf.club.ClubGame_pb.ClubGame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.leyou.common.protobuf.club.ClubGame_pb.ClubGame buildPartial() {
        com.leyou.common.protobuf.club.ClubGame_pb.ClubGame result = new com.leyou.common.protobuf.club.ClubGame_pb.ClubGame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gameType_ = gameType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.onlineTableNum_ = onlineTableNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.totalTable_ = totalTable_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.gameConf_ = gameConf_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leyou.common.protobuf.club.ClubGame_pb.ClubGame) {
          return mergeFrom((com.leyou.common.protobuf.club.ClubGame_pb.ClubGame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.leyou.common.protobuf.club.ClubGame_pb.ClubGame other) {
        if (other == com.leyou.common.protobuf.club.ClubGame_pb.ClubGame.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasGameType()) {
          setGameType(other.getGameType());
        }
        if (other.hasOnlineTableNum()) {
          setOnlineTableNum(other.getOnlineTableNum());
        }
        if (other.hasTotalTable()) {
          setTotalTable(other.getTotalTable());
        }
        if (other.hasGameConf()) {
          setGameConf(other.getGameConf());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGameType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gameType_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              onlineTableNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              totalTable_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              gameConf_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // required int32 gameType = 3;
      private int gameType_ ;
      public boolean hasGameType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getGameType() {
        return gameType_;
      }
      public Builder setGameType(int value) {
        bitField0_ |= 0x00000004;
        gameType_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gameType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 onlineTableNum = 4;
      private int onlineTableNum_ ;
      public boolean hasOnlineTableNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getOnlineTableNum() {
        return onlineTableNum_;
      }
      public Builder setOnlineTableNum(int value) {
        bitField0_ |= 0x00000008;
        onlineTableNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearOnlineTableNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        onlineTableNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 totalTable = 5;
      private int totalTable_ ;
      public boolean hasTotalTable() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getTotalTable() {
        return totalTable_;
      }
      public Builder setTotalTable(int value) {
        bitField0_ |= 0x00000010;
        totalTable_ = value;
        onChanged();
        return this;
      }
      public Builder clearTotalTable() {
        bitField0_ = (bitField0_ & ~0x00000010);
        totalTable_ = 0;
        onChanged();
        return this;
      }
      
      // optional string gameConf = 6;
      private java.lang.Object gameConf_ = "";
      public boolean hasGameConf() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getGameConf() {
        java.lang.Object ref = gameConf_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gameConf_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGameConf(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        gameConf_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameConf() {
        bitField0_ = (bitField0_ & ~0x00000020);
        gameConf_ = getDefaultInstance().getGameConf();
        onChanged();
        return this;
      }
      void setGameConf(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        gameConf_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ClubGame)
    }
    
    static {
      defaultInstance = new ClubGame(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ClubGame)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClubGame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClubGame_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023club/ClubGame.proto\"t\n\010ClubGame\022\n\n\002id\030" +
      "\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010gameType\030\003 \002(\005\022\026\n" +
      "\016onlineTableNum\030\004 \001(\005\022\022\n\ntotalTable\030\005 \001(" +
      "\005\022\020\n\010gameConf\030\006 \001(\tB-\n\036com.leyou.common." +
      "protobuf.clubB\013ClubGame_pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClubGame_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClubGame_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClubGame_descriptor,
              new java.lang.String[] { "Id", "Name", "GameType", "OnlineTableNum", "TotalTable", "GameConf", },
              com.leyou.common.protobuf.club.ClubGame_pb.ClubGame.class,
              com.leyou.common.protobuf.club.ClubGame_pb.ClubGame.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
